/*
PAQUETE 1 - ESPORT_MOH_1

ESTE CONTENDRA UN PROCEDIMIENTO ALMACENADO LLAMADO PROCE_generarAutoUserPass

POR MIGUEL OLMO HERNANDO - 04/04/2018
*/

-- INICIO CABECERA PAQUETE
CREATE OR REPLACE PACKAGE ESPORT_MOH_1
IS
  PROCEDURE PROCE_generarAutoUserPass(v_dni IN VARCHAR , v_nombre IN VARCHAR, v_apellido IN VARCHAR, v_tipo IN VARCHAR, v_codlogin OUT INTEGER);
END ESPORT_MOH_1;
-- FIN CABECERA DEL PAQUETE

-- INICIO CUERPO DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY ESPORT_MOH_1 
IS
  PROCEDURE PROCE_generarAutoUserPass(v_dni IN VARCHAR , v_nombre IN VARCHAR, v_apellido IN VARCHAR, v_tipo IN VARCHAR, v_codlogin OUT INTEGER) AS
    usuario VARCHAR(30);
    contrasenia VARCHAR(30);
BEGIN 
  usuario := UPPER(v_dni);
  contrasenia := UPPER(substr(v_nombre,1,1) || v_apellido);
   INSERT INTO login (usuario, passwd, tipo) VALUES (usuario, contrasenia, v_tipo) RETURNING codlogin INTO v_codlogin;
EXCEPTION 
  WHEN OTHERS THEN 
    RAISE_APPLICATION_ERROR (-20100, 'ERROR INEXPERADO AL GENERAR EL LOGIN - USUARIO/CONTRASENIA: '|| SQLERRM);
  END PROCE_generarAutoUserPass;
END ESPORT_MOH_1;
-- FIN CUERPO DEL PAQUETE

/*
COMPROBACIONES PARA LLAMAR AL PROCEDIMIENTO ALMCENADO PROCE_generarAutoUserPass
MEDIANTE UN PROCEDIMIENTO ANONIMO*/
/*

SET SERVEROUTPUT ON

DECLARE
  v_codlogin INTEGER;
BEGIN
  generarAutoUserPass ('12345678A', 'Miguel', 'Miguel', 'A',v_codlogin);
END;

*/
