(codJugador, dni, nombre, apellido, nickname, sueldo, fechaNacimiento, nacionalidad, posicion)

INSERT INTO jugador VALUES (DEFAULT, '', '12345678A', 'nombre', 'apellido', 'nickname', 40000, to_date('10/10/1000', 'dd/mm/YYYY'), 'nacionalidad', 'j')
INSERT INTO jugador VALUES (DEFAULT, '', 'LeBron James','Houston','6-8',250,'F','Cavaliers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Pau Gasol','Spain','7-0',250,'F-C','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Marc Gasol','Spain','7-0',250,'F-C','Lakers');


INSERT INTO jugador VALUES (DEFAULT, '', 'Corey Brever','Florida','6-9',185,'F-G','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Greg Buckner','Clemson','6-4',210,'G-F','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Michael Doleac','Utah','6-11',262,'C','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Randy Foye','Villanova','6-4',213,'G','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Ryan Gomes','Providence','6-7',250,'F','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Marko Jaric','Serbia','6-7',224,'G','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Al Jefferson','Prentiss Hs','6-10',265,'C-F','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Mark Madsen','Stanford','6-9',250,'C-F','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Rashard McCants','North Carolina','6-4',21,'G','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Chris Richard ','Florida','6-9',270,'F','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Craig Smith','Boston College','6-8',250,'F-C','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Kirk Snyder','Nevada-Reno','6-6',225,'G','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Sebastian Telfair','Abraham Lincoln HS','6-0',175,'G','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Antoine Walker','Kentucky','6-9',245,'F','Timberwolves');
INSERT INTO jugador VALUES (DEFAULT, '', 'Elton brand','duke','6-8',254,'F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Paul Davis','Michigan','6-11',270,'c','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Dan Dickau','Gonzaga','6-0',180,'G','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Nick Fazekas','Nevada-Reno','6-11',235,'F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Chris Kaman','Central Michigan','7-0',265,'C','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Brevin Knight','Stanford','5-10',170,'G','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Shaun Livingston','Peoria Central','6-7',182,'G','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Corey Maggette','duke','6-6',225,'F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Cuttino Mobley','Rhode Island','6-4',215,'G','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Smush Parker','Fordham','6-4',190,'G','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Josh Powell','North Carolina State','6-9',240,'C-F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Quinton Ross','Southern Methodist','6-6',193,'G-F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Tim Thomas','Villanova','6-10',240,'F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'al thornton','Florida State','6-8',220,'F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Marcus Williams','Arizona','6-7',207,'F','Clippers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Andre Brown','De Paul','6-9',245,'F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Kwame Brown','Glynn Academy','6-11',270,'C','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Brian Cardinal','Purdue','6-8',245,'F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Jason Collins','Stanford','7-0',255,'C-F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Mike Conley','Ohio State','6-1',180,'G','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Javaris Crittenton','Georgia Tech','6-5',200,'G','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Rudy Gay','Connecticut','6-8',222,'F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Casey Jacobsen','Stanford','6-6',215,'g','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Kyle Lowry','Villanova','6-0',175,'G','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Aaron Mckie','Temple','6-5',209,'G','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Darko Milicic','Serbia Montenegro','7-0',275,'C-F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Mike Miller','Florida','6-8',218,'G-F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Juan Carlos Navarro','Spain','6-3',170,'G','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Hakim Warrick','Syracuse','6-9',215,'F','Grizzlies');
INSERT INTO jugador VALUES (DEFAULT, '', 'Trevor Ariza','UCLA','6-8',210,'F','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Kobe Bryant','Lower Merion HS (PA)','6-6',205,'G','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Andrew Bynum','St. Joseph HS (NJ)','7-0',285,'C','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Jordan Farmar','UCLA','6-2',180,'G','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Derek Fisher','Arkansas-Little Rock','6-1',210,'G','Lakers');

INSERT INTO jugador VALUES (DEFAULT, '', 'Didier Ilunga-Mbenga','Congo','7-0',255,'C','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Coby Karl','Boise State','6-5',215,'G','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Chris Mihm','Texas','7-0',265,'C','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Ira Newble','Miami(Ohia)','6-7',220,'G-F','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Lamar Odom','Rhode Island','6-10',230,'F','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Vladimir Radmanovic','Serbia Montenegro','6-10',235,'F','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Ronny Turiaf','Gonzaga','6-10',250,'F-C','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Sasha Vujacic','Slovenia','6-7',205,'G','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Luke Walton','Arizona','6-8',235,'F','Lakers');
INSERT INTO jugador VALUES (DEFAULT, '', 'Andrea Bargnani','Italy','7-0',250,'C-F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Maceo Baston','Michigan','6-10',230,'C-F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Primoz Brezec','Slovenia','7-1',255,'C','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Jose Calderon','Spain','6-3',210,'G','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Carlos Delfino','Argentina','6-6',230,'G','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'T.J. Ford','Texas','6-0',165,'G','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Jorge Garbajosa','Spain','6-9',245,'F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Joey Graham','Oklahoma State','6-7',225,'F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Kris Humphries','Minnesota','6-9',235,'F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Linton Johnson III','Tulane','6-8',205,'F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Jason Kapono','UCLA','6-8',215,'F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Jamario Moon','Merdian CC (MS)','6-8',205,'F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Rasho Nesterovic','Slovenia','7-0',255,'C','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Anthony Parker','Bradley','6-6',215,'G-F','Raptors');
INSERT INTO jugador VALUES (DEFAULT, '', 'Renaldo Balkman','South Carolina','6-8',202,'F','Knicks');
INSERT INTO jugador VALUES (DEFAULT, '', 'Wilson Chandler','DePaul','6-8',220,'F','Knicks');
INSERT INTO jugador VALUES (102,'Mardy Collins','Temple','6-6',220,'G','Knicks');
INSERT INTO jugador VALUES (103,'Jamal Crawford','Michigan','6-5',220,'G','Knicks');
INSERT INTO jugador VALUES (104,'Eddy Curry','Thornwood HS','6-11',285,'C','Knicks');
INSERT INTO jugador VALUES (105,'Jerome James','Florida AM','7-1',285,'C','Knicks');
INSERT INTO jugador VALUES (106,'Jared Jeffries','Indiana','6-11',240,'F','Knicks');
INSERT INTO jugador VALUES (107,'Fred Jones','Oregon','6-2',225,'G','Knicks');
INSERT INTO jugador VALUES (108,'David Lee','Florida','6-9',240,'F','Knicks');
INSERT INTO jugador VALUES (109,'Stephon Marbury','Georgia Tech','6-2',205,'G','Knicks');
INSERT INTO jugador VALUES (110,'Randolph Morris','Kentucky','6-11',260,'C','Knicks');
INSERT INTO jugador VALUES (111,'Zach Randolph','Michigan State','6-9',260,'F','Knicks');
INSERT INTO jugador VALUES (112,'Quentin Richardson','DePaul','6-6',235,'F-G','Knicks');
INSERT INTO jugador VALUES (113,'Nate Robinson','Washington','5-9',180,'G','Knicks');
INSERT INTO jugador VALUES (114,'Malik Rose','Drexel','6-7',255,'F','Knicks');
INSERT INTO jugador VALUES (120,'Louis Amundson',' Nevada-Las Vegas',' 6-9',225,'F','76ers');
INSERT INTO jugador VALUES (121,'Calvin Booth','Penn State','6-11',250,'C','76ers');
INSERT INTO jugador VALUES (122,'Rodney Carney','Memphis','6-7',204,'F','76ers');
INSERT INTO jugador VALUES (123,'Samuel Dalembert','Seton Hall','6-11',250,'C','76ers');
INSERT INTO jugador VALUES (124,'Reggie Evans','Iowa','6-8',245,'F','76ers');
INSERT INTO jugador VALUES (125,'Willie Green','Detroit Mercy','6-3',201,'G','76ers');
INSERT INTO jugador VALUES (126,'Herbert Hill','Providence','6-10',240,'F-C','76ers');
INSERT INTO jugador VALUES (127,'Andre Iguodala','Arizona','6-6',207,'F-G','76ers');
INSERT INTO jugador VALUES (128,'Andre Miller','Utah','6-2',200,'G','76ers');
INSERT INTO jugador VALUES (129,'Kevin Ollie','Connecticut','6-2',195,'G','76ers');
INSERT INTO jugador VALUES (130,'Shavlik Randolph','Duke','6-10',240,'F','76ers');
INSERT INTO jugador VALUES (131,'Jason Smith','Colorado Sate','7-0',240,'F','76ers');
INSERT INTO jugador VALUES (132,'Louis Williams','South Gwinnett HS','6-2',175,'G','76ers');
INSERT INTO jugador VALUES (133,'Thaddeus Young','Georgio Tech','6-8',220,'F','76ers');
INSERT INTO jugador VALUES (150,'Lance Allred','Weber State','6-11',250,'C','Cavaliers');
INSERT INTO jugador VALUES (151,'Devin Brown','Texas-San Antonio','6-5',210,'G','Cavaliers');
INSERT INTO jugador VALUES (152,'Daniel Gibson','Texas','6-2',194,'G','Cavaliers');
INSERT INTO jugador VALUES (153,'Zydrunas Ilgauskas','St. Vincent-St. Mary','7-3',260,'C','Cavaliers');

INSERT INTO jugador VALUES (155,'Damon Jones','Saint Joseph''s','6-3',195,'G','Cavaliers');
INSERT INTO jugador VALUES (156,'Dwayne Jones','Serbia','6-11',251,'C-F','Cavaliers');
INSERT INTO jugador VALUES (157,'Aleksandar Pavlovic','Maryland','6-7',239,'G-F','Cavaliers');
INSERT INTO jugador VALUES (158,'Joe Smith','Michigan State','6-10',225,'F-C','Cavaliers');
INSERT INTO jugador VALUES (159,'Eric Snow','Miami ','6-3',205,'G','Cavaliers');
INSERT INTO jugador VALUES (160,'Wally Szczerbiak','Brazil','6-7',245,'F','Cavaliers');
INSERT INTO jugador VALUES (161,'Anderson Varejao','Merdian CC (MS)','6-10',240,'C-F','Cavaliers');
INSERT INTO jugador VALUES (162,'Ben Wallace','Virginia Union','6-9',240,'C-F','Cavaliers');
INSERT INTO jugador VALUES (163,'Delonte West','Saint Joseph''s','6-3',180,'G','Cavaliers');
INSERT INTO jugador VALUES (181,'Derek Anderson','Kentucky','6-5',195,'G','Bobcats');
INSERT INTO jugador VALUES (182,'Earl Boykins','Eastern michigan','5-5',133,'G','Bobcats');
INSERT INTO jugador VALUES (183,'Matt Carroll','Notre Dame','6-6',212,'G','Bobcats');
INSERT INTO jugador VALUES (184,'Jermareo Davidson','Alabama','6-10',230,'F','Bobcats');
INSERT INTO jugador VALUES (185,'Jared Dudley','Boston College','6-7',225,'F','Bobcats');
INSERT INTO jugador VALUES (186,'Raymond Felton','North Carolina','6-1',198,'G','Bobcats');
INSERT INTO jugador VALUES (187,'Othella Harrington','Georgetown','6-9',235,'F-C','Bobcats');
INSERT INTO jugador VALUES (188,'Ryan Hollins','Ucla','7-0',230,'C','Bobcats');
INSERT INTO jugador VALUES (189,'Sean May','North Carolina','6-9',266,'F-C','Bobcats');
INSERT INTO jugador VALUES (190,'Nazr Mohammed','Kentucky','6-10',250,'C','Bobcats');
INSERT INTO jugador VALUES (191,'Adam Morrison','Gonzaga','6-8',205,'F','Bobcats');
INSERT INTO jugador VALUES (192,'Emeka Okafor','Connecticut','6-10',255,'F-C','Bobcats');
INSERT INTO jugador VALUES (193,'Jason Richardson','Michigan State','6-6',225,'G-F','Bobcats');
INSERT INTO jugador VALUES (194,'Gerald Wallace','Alabama','6-7',220,'F','Bobcats');
INSERT INTO jugador VALUES (201,'Charlie Bell','Michigan State','6-3',200,'G','Bucks');
INSERT INTO jugador VALUES (202,'Andrew Bouqt','Utah','7-0',260,'C','Bucks');
INSERT INTO jugador VALUES (203,'Dan Gadzuric','Ucla','6-11',245,'C','Bucks');
INSERT INTO jugador VALUES (204,'Royal Ivey','Texas','6-4',215,'G','Bucks');
INSERT INTO jugador VALUES (205,'Desmond Mason','Oklahoma State','6-5',222,'F','Bucks');
INSERT INTO jugador VALUES (206,'Michael Redd','Ohio State','6-6',215,'G','Bucks');
INSERT INTO jugador VALUES (207,'Michael Ruffin','Tulsa','6-8',248,'F-C','Bucks');
INSERT INTO jugador VALUES (208,'Ramon Sessions','Nevava-Reno','6-3',190,'G','Bucks');
INSERT INTO jugador VALUES (209,'Bobby Simmons','DePaul','6-6',230,'F','Bucks');
INSERT INTO jugador VALUES (210,'Awvee Store','Arizona State','6-6',225,'F-G','Bucks');
INSERT INTO jugador VALUES (211,'Charlie Villanueva','Connecticut','6-11',232,'F','Bucks');
INSERT INTO jugador VALUES (212,'Jake Voskuhl','Connecticut','6-11',255,'C','Bucks');
INSERT INTO jugador VALUES (213,'Mo Williams','Alabama','6-1',185,'G','Bucks');
INSERT INTO jugador VALUES (214,'Yi Jianlian','Connecticut','7-0',238,'F','Bucks');
INSERT INTO jugador VALUES (220,'Shannon Brown','Michigan State','6-4',211,'G','Bulls');
INSERT INTO jugador VALUES (221,'JamesOn Curry','Oklahoma Stare','6-3',190,'G','Bulls');
INSERT INTO jugador VALUES (222,'Luol Deng','Duke','6-9',220,'F','Bulls');
INSERT INTO jugador VALUES (223,'Chris Duhon','Duke','6-1',185,'G','Bulls');
INSERT INTO jugador VALUES (224,'Drew Gooden','Kansas','6-10',250,'F','Bulls');
INSERT INTO jugador VALUES (225,'Ben Gordon','Connecticut','6-3',200,'G','Bulls');
INSERT INTO jugador VALUES (226,'Aaron Gray','Pittsburgh','7-0',270,'C','Bulls');
INSERT INTO jugador VALUES (227,'Kirk Hinrich','Kansas','6-3',190,'G','Bulls');
INSERT INTO jugador VALUES (228,'Larry Hughes','St.Luis','6-5',185,'G','Bulls');
INSERT INTO jugador VALUES (229,'Demetris Nichols','Syracuse','6-8',216,'F','Bulls');
INSERT INTO jugador VALUES (230,'Joakin Noah','Florida','6-11',232,'C-F','Bulls');
INSERT INTO jugador VALUES (231,'Andres Nocioni','Argentina','6-7',225,'F','Bulls');
INSERT INTO jugador VALUES (232,'Thabo Sefolosha','Switzerland','6-7',215,'G','Bulls');
INSERT INTO jugador VALUES (233,'Cedric Simmons','North Carolina State','6-9',235,'F','Bulls');
INSERT INTO jugador VALUES (234,'Tyrus Thonas','Louisiana State','6-9',215,'F','Bulls');
INSERT INTO jugador VALUES (240,'Ray Allen','Connecticut','6-5',205,'G','Celtics');
INSERT INTO jugador VALUES (241,'Tony Allen','Oklahoma State','6-4',213,'G','Celtics');
INSERT INTO jugador VALUES (242,'P.J.Brown','Louisiana State','6-11',239,'F-C','Celtics');
INSERT INTO jugador VALUES (243,'Sam Cassell','Florida State','6-3',185,'G','Celtics');
INSERT INTO jugador VALUES (244,'Glen Davis','Louisiana State','6-9',289,'F','Celtics');
INSERT INTO jugador VALUES (245,'Kevin Garnett','Farragut Academy','6-11',220,'F','Celtics');
INSERT INTO jugador VALUES (246,'Eddie House','Arizona State','6-1',175,'G','Celtics');
INSERT INTO jugador VALUES (247,'Kendrick Perkins','Clifton J.Ozen HS','6-10',264,'C','Celtics');
INSERT INTO jugador VALUES (248,'Paul Pierce','Kansas','6-7',230,'F','Celtics');
INSERT INTO jugador VALUES (249,'Scot Pollard','Kansas','6-11',278,'C-F','Celtics');
INSERT INTO jugador VALUES (250,'James Posey','Xavier','6-8',217,'F','Celtics');
INSERT INTO jugador VALUES (251,'Leon Powe','California','6-8',240,'F','Celtics');
INSERT INTO jugador VALUES (252,'Gabe Pruitt','USC','6-4',170,'G','Celtics');
INSERT INTO jugador VALUES (253,'Rajon Rondo','Kentucky','6-1',171,'G','Celtics');
INSERT INTO jugador VALUES (254,'Brian Scalabrine','USC','6-9',235,'F-C','Celtics');
INSERT INTO jugador VALUES (261,'Mike Bibby','Arizona','6-1',190,'G','Hawks');
INSERT INTO jugador VALUES (262,'Josh Childress','Stanford','6-8',210,'G-F','Hawks');
INSERT INTO jugador VALUES (263,'Speedy Claxton','Hofstra','6-1',170,'G','Hawks');
INSERT INTO jugador VALUES (264,'Al Horford','Florida','6-10',245,'C-F','Hawks');
INSERT INTO jugador VALUES (265,'Joe Johnson','Arkansas','6-7',235,'G','Hawks');
INSERT INTO jugador VALUES (266,'Solomon Jones','South Florida','6-10',230,'F','Hawks');
INSERT INTO jugador VALUES (267,'Acie Law','Texas AM','6-3',195,'G','Hawks');
INSERT INTO jugador VALUES (268,'Zaza Pachulia','Georgia','6-11',280,'C','Hawks');
INSERT INTO jugador VALUES (269,'Jeremy Richardson','Delta State','6-7',195,'G-F','Hawks');
INSERT INTO jugador VALUES (270,'Josh Smith','Oak Hill Academy','6-9',235,'F','Hawks');
INSERT INTO jugador VALUES (271,'Salim Stoudamire','Arizona','6-1',175,'G','Hawks');
INSERT INTO jugador VALUES (272,'Mario West','Georgia Tech','6-5',210,'G','Hawks');
INSERT INTO jugador VALUES (273,'Marvin Williams','North Carolina','6-9',230,'F','Hawks');
INSERT INTO jugador VALUES (281,'Blake Ahearn','Missouri State','6-2',190,'G','Heat');
INSERT INTO jugador VALUES (282,'joel Anthony','Nevada-Las vegas','6-9',245,'C','Heat');
INSERT INTO jugador VALUES (283,'Marcus Banks','Nevada-Las vegas','6-2',212,'G','Heat');
INSERT INTO jugador VALUES (284,'Earl Barron','Memphis','7-0',245,'C-F','Heat');
INSERT INTO jugador VALUES (285,'Mark Blount','Pittsburgh','7-0',250,'C-F','Heat');
INSERT INTO jugador VALUES (286,'Daequan Cook','Ohio State','6-5',205,'G','Heat');
INSERT INTO jugador VALUES (287,'Ricky Davis','lowa','6-7',250,'F-G','Heat');
INSERT INTO jugador VALUES (288,'Udonis Haslem','Florida','6-8',235,'F','Heat');
INSERT INTO jugador VALUES (289,'Alexander Johnson','Florida State','6-9',230,'F','Heat');
INSERT INTO jugador VALUES (290,'Stephane Lasme','Massachusetts','6-8',215,'F','Heat');
INSERT INTO jugador VALUES (291,'Shawn Marion','UNLV','6-7',230,'F','Heat');
INSERT INTO jugador VALUES (292,'Alonzo Mourning','Georgetown','6-10',261,'C','Heat');
INSERT INTO jugador VALUES (293,'Chris Quinn','Notre dame','6-2',175,'G','Heat');
INSERT INTO jugador VALUES (294,'Dwyane Wade','Marquette','6-4',216,'G','Heat');
INSERT INTO jugador VALUES (295,'Jason Williams','Florida','6-1',180,'G','Heat');
INSERT INTO jugador VALUES (296,'Dorell Wright','South Kent','6-9',210,'F','Heat');
INSERT INTO jugador VALUES (300,'Shareef Abdur-Rahim',' California',' 6-9',245,'F','Kings');
INSERT INTO jugador VALUES (301,'Ron Artest','St.Johns','6-7',248,'F','Kings');
INSERT INTO jugador VALUES (302,'Quincy Douby','Rutgers','6-3',175,'G','Kings');
INSERT INTO jugador VALUES (303,'Francisco Garcia','Lousiville','6-7',195,'F-G','Kings');
INSERT INTO jugador VALUES (304,'Spencer Hawes','Washingtong','7-0',245,'C','Kings');
INSERT INTO jugador VALUES (305,'Anthony Johnson','Charleston','6-3',195,'G','Kings');
INSERT INTO jugador VALUES (306,'Kevin Martin','Western Carolina','6-7',185,'G','Kings');
INSERT INTO jugador VALUES (307,'Brad Miller','Purdue','7-0',261,'C','Kings');
INSERT INTO jugador VALUES (308,'Mikki More','Nebraska','7-0',225,'F-C','Kings');
INSERT INTO jugador VALUES (309,'mike john salmons','Miami','6-6',207,'G-F','Kings');
INSERT INTO jugador VALUES (310,'Keny Thomas','New Mexico','6-7',245,'F','Kings');
INSERT INTO jugador VALUES (311,'Beno Udrih','Slovenia','6-3',205,'G','Kings');
INSERT INTO jugador VALUES (312,'Shelden Williams','Duke','6-9',250,'F-C','Kings');
INSERT INTO jugador VALUES (313,'Lorenzen Wright','Memphis','6-11',255,'C','Kings');
INSERT INTO jugador VALUES (314,'Brian Scalabrine','USC','6-9',235,'F-C','Kings');
INSERT INTO jugador VALUES (320,'Chris Andersen','Blinn Coll','6-10',228,'F-C','Hornets');
INSERT INTO jugador VALUES (321,'Hilton Armstrong','Connecticut','6-11',235,'C-F','Hornets');
INSERT INTO jugador VALUES (322,'Ryan Bowen','Iowa','6-10',218,'F','Hornets');
INSERT INTO jugador VALUES (323,'Rasual Butler','La Salle','6-7',205,'F-G','Hornets');
INSERT INTO jugador VALUES (324,'Tyson Chandler','Dominguez HS','7-1',235,'C','Hornets');
INSERT INTO jugador VALUES (325,'Melvin Ely','Fresno State','6-10',261,'C-F','Hornets');
INSERT INTO jugador VALUES (326,'Mike James','Duquesne','6-2',188,'G','Hornets');
INSERT INTO jugador VALUES (327,'Jannero Pargo','Arkansas','6-1',175,'G','Hornets');
INSERT INTO jugador VALUES (328,'Chris Paul','Wake Forest','6-0',175,'G','Hornets');
INSERT INTO jugador VALUES (329,'Morris Peterson','Michigan State','6-7',220,'G','Hornets');
INSERT INTO jugador VALUES (330,'Peja Stojakovic','Serbia','6-10',229,'F','Hornets');
INSERT INTO jugador VALUES (331,'Bonzi Wells','Ball State','6-5',210,'G-F','Hornets');
INSERT INTO jugador VALUES (332,'David West','Xavier','6-9',240,'F','Hornets');
INSERT INTO jugador VALUES (333,'Julian Wright','Kansas','6-8',225,'F','Hornets');
INSERT INTO jugador VALUES (340,'Rafer ALston','Fresno State','6-2',175,'G','Rockets');
INSERT INTO jugador VALUES (341,'Shane Battier','Duke','6-8',220,'F','Rockets');
INSERT INTO jugador VALUES (342,'Aaron Brooks','Oregon','6-0',161,'G','Rockets');
INSERT INTO jugador VALUES (343,'Steve Francis','Maryland','6-3',210,'G','Rockets');
INSERT INTO jugador VALUES (344,'Mike Harris','Rice','6-6',240,'F','Rockets');
INSERT INTO jugador VALUES (345,'Chuck Hayes','Kentucky','6-6',238,'F','Rockets');
INSERT INTO jugador VALUES (346,'Luther Head','Illinois','6-3',185,'G','Rockets');
INSERT INTO jugador VALUES (347,'Bobby Jackson','Minnesota','6-1',185,'G','Rockets');
INSERT INTO jugador VALUES (348,'Carl Landry','Purdue','6-9',248,'F','Rockets');
INSERT INTO jugador VALUES (349,'Tracy McGrady','Mount Zion Christian','6-8',223,'G','Rockets');
INSERT INTO jugador VALUES (350,'Dikembre Mutombo','Georgetown','7-2',260,'C','Rockets');
INSERT INTO jugador VALUES (351,'Steve NOvak','Marquette','6-10',220,'F','Rockets');
INSERT INTO jugador VALUES (352,'Luis Scola','Argentina','6-9',245,'F-C','Rockets');
INSERT INTO jugador VALUES (353,'Loren Woods','Arizona','7-2',260,'C','Rockets');
INSERT INTO jugador VALUES (354,'Yao Ming','China','7-6',310,'C','Rockets');
INSERT INTO jugador VALUES (361,'Brent Barry','Oregon State','6-7',210,'G','Spurs');
INSERT INTO jugador VALUES (362,'Matt Bonner','Florida','6-10',240,'C-F','Spurs');
INSERT INTO jugador VALUES (363,'Bruce Bowen','Cal State Fullerton','6-7',200,'F','Spurs');
INSERT INTO jugador VALUES (364,'Tim Duncan','Wake Forest','6-11',260,'F-C','Spurs');
INSERT INTO jugador VALUES (365,'Michael Finley','Wisconsin','6-7',225,'G-F','Spurs');
INSERT INTO jugador VALUES (366,'Manu Ginobili','Argentina','6-6',205,'G','Spurs');
INSERT INTO jugador VALUES (367,'Robert Horry','Alabama','6-10',240,'F-C','Spurs');
INSERT INTO jugador VALUES (368,'Bobby Jones','Washington','6-7',215,'F','Spurs');
INSERT INTO jugador VALUES (369,'Ian Mahinmi','Frande','6-11',230,'C','Spurs');
INSERT INTO jugador VALUES (370,'Fabricio Oberto','Argentina','6-10',245,'C','Spurs');
INSERT INTO jugador VALUES (371,'Tony Parker','France','6-2',180,'G','Spurs');
INSERT INTO jugador VALUES (372,'Damon Stoudamire','Arizona','5-10',171,'G','Spurs');
INSERT INTO jugador VALUES (373,'Kurt Thomas','Texas Christian','6-9',235,'C-F','Spurs');
INSERT INTO jugador VALUES (374,'Ime Udoka','Portland State','6-5',220,'F','Spurs');
INSERT INTO jugador VALUES (375,'Jacque Vaughn','Kansas','6-1',190,'G','Spurs');
INSERT INTO jugador VALUES (381,'LaMarcus Aldridge','Texas','6-11',245,'F-C','Trail Blazers');
INSERT INTO jugador VALUES (382,'Steve Blake','Maryland','6-3',172,'G','Trail Blazers');
INSERT INTO jugador VALUES (383,'Channing Frye','Arizona','6-11',248,'C','Trail Blazers');
INSERT INTO jugador VALUES (384,'Jarrett Jack','Georgia Tech','6-3',197,'G','Trail Blazers');
INSERT INTO jugador VALUES (385,'James Jones','Miami (Fla)','6-8',220,'F','Trail Blazers');
INSERT INTO jugador VALUES (386,'Raef LaFremtz','Kansas','6-11',245,'F','Trail Blazers');
INSERT INTO jugador VALUES (387,'Josh McRoberts','Duke','6-10',240,'F','Trail Blazers');
INSERT INTO jugador VALUES (388,'Darius Miles','East St.Louis','6-9',222,'F','Trail Blazers');
INSERT INTO jugador VALUES (389,'Greg Oden','Ohio State','7-0',250,'C','Trail Blazers');
INSERT INTO jugador VALUES (390,'Travis Outlaw','Starville HS','6-9',215,'F','Trail Blazers');
INSERT INTO jugador VALUES (391,'Joel Przybilla','Minnesota','7-1',255,'C','Trail Blazers');
INSERT INTO jugador VALUES (392,'Sergio Rodriguez','Spain','6-3',168,'G','Trail Blazers');
INSERT INTO jugador VALUES (393,'Brandon Roy','Washington','6-6',229,'G-F','Trail Blazers');
INSERT INTO jugador VALUES (394,'Von Wafer','Florida State','6-5',210,'G','Trail Blazers');
INSERT INTO jugador VALUES (395,'Martell Webster','Seattle Prep HS','6-7',229,'F-G','Trail Blazers');
INSERT INTO jugador VALUES (400,'Gilbert Arenas','Arizona','6-4',215,'G','Wizards');
INSERT INTO jugador VALUES (401,'Andray Blatche','South Kent Prep','6-11',248,'F','Wizards');
INSERT INTO jugador VALUES (402,'Caron Butler','Connecticut','6-7',228,'F','Wizards');
INSERT INTO jugador VALUES (403,'Antonio Daniels','Bowling Green','6-4',205,'G','Wizards');
INSERT INTO jugador VALUES (404,'Brendan Haywood','North Carolina','7-0',263,'C','Wizards');
INSERT INTO jugador VALUES (405,'Antawn Jamison','North Carolina','6-9',235,'F','Wizards');
INSERT INTO jugador VALUES (406,'Roger Mason','Virginia','6-5',212,'G','Wizards');
INSERT INTO jugador VALUES (407,'Dominic McGuire','Fresno State','6-9',220,'F','Wizards');
INSERT INTO jugador VALUES (408,'Oleksiy Pecherov','Donetsk','7-0',234,'C-F','Wizards');
INSERT INTO jugador VALUES (409,'Darius Songaila','Wake Forest','6-9',248,'F','Wizards');
INSERT INTO jugador VALUES (410,'DeShawn Stevenson','Washington Union HS','6-5',218,'G','Wizards');
INSERT INTO jugador VALUES (411,'Etan Thomas','Syracuse','6-10',260,'C','Wizards');
INSERT INTO jugador VALUES (412,'Nick Young','USC','6-6',200,'G','Wizards');
INSERT INTO jugador VALUES (420,'Carlos Arroyo','Florida Internationa',' 6-2',202,'G','Magic');
INSERT INTO jugador VALUES (421,'James Augustine','Illinois','6-10',235,'F','Magic');
INSERT INTO jugador VALUES (422,'Tony Battie','Texas Tech','6-11',240,'F-C','Magic');
INSERT INTO jugador VALUES (423,'Keith Bogans','Kentucky','6-5',215,'G-F','Magic');
INSERT INTO jugador VALUES (424,'Brian Cook','Illinois','6-9',250,'F','Magic');
INSERT INTO jugador VALUES (425,'Kenyon Dooling','Missouri','6-3',195,'G','Magic');
INSERT INTO jugador VALUES (426,'Maurice Evans','Texas','6-5',220,'G','Magic');
INSERT INTO jugador VALUES (427,'Adonal Foyle','Colgate','6-10',270,'C','Magic');
INSERT INTO jugador VALUES (428,'Pat Garrity','Notre Dame','6-9',238,'F','Magic');
INSERT INTO jugador VALUES (429,'Marcin Gortat','Poland','7-0',240,'F-C','Magic');
INSERT INTO jugador VALUES (430,'Dwight Howard','SW Atlanta Crhistian','6-11',265,'F-C','Magic');
INSERT INTO jugador VALUES (431,'Rashard Lewis','None','6-10',230,'F','Magic');
INSERT INTO jugador VALUES (432,'Jammer Nelson','Saint Josephs','6-0',190,'G','Magic');
INSERT INTO jugador VALUES (433,'J.J.Redick','Duke','6-4',190,'G','Magic');
INSERT INTO jugador VALUES (434,'Hedo Turkoglu','Turkey','6-10',220,'F','Magic');
INSERT INTO jugador VALUES (440,'Malik Allen','Villanova','6-10',255,'F','Mavericks');
INSERT INTO jugador VALUES (441,'Jose Barea','Northeastern','6-0',175,'G','Mavericks');
INSERT INTO jugador VALUES (442,'Brandon Bass','Louisiana State','6-8',240,'F','Mavericks');
INSERT INTO jugador VALUES (443,'Erick Dampier','Mississippi','6-11',265,'C','Mavericks');
INSERT INTO jugador VALUES (444,'Josh Howard','Wake Forest','6-5',210,'F-G','Mavericks');
INSERT INTO jugador VALUES (445,'Juwan Howard','Michigan','6-9',253,'F','Mavericks');
INSERT INTO jugador VALUES (446,'Eddie Jones','Temple','6-6',200,'G-F','Mavericks');
INSERT INTO jugador VALUES (447,'Jason Kidd','California','6-4',210,'G','Mavericks');
INSERT INTO jugador VALUES (448,'Tyronn Lue','Nebraska','6-0',175,'G','Mavericks');
INSERT INTO jugador VALUES (449,'Jamaal Magloire','Kentucky','6-11',265,'C','Mavericks');
INSERT INTO jugador VALUES (450,'Dirk Nowitzki','Germany','7-0',245,'F','Mavericks');
INSERT INTO jugador VALUES (451,'Jerry Stackhouse','North Carolina','6-6',218,'G-F','Mavericks');
INSERT INTO jugador VALUES (452,'Jason Terry','Arizona','6-2',180,'G','Mavericks');
INSERT INTO jugador VALUES (453,'Antoine Wright','Texas','6-7',215,'G-F','Mavericks');
INSERT INTO jugador VALUES (454,'Devean George','Augsburg','6-8',235,'F-G','Mavericks');
INSERT INTO jugador VALUES (461,'Maurice Ager','Michigan State','6-5',202,'F-G','Nets');
INSERT INTO jugador VALUES (462,'Darrel Armstrong','Fayetteville State','6-1',180,'G','Nets');
INSERT INTO jugador VALUES (463,'Josh Boone','Connecticut','6-10',237,'C','Nets');
INSERT INTO jugador VALUES (464,'Vince Carter','North Carolina','6-6',220,'G','Nets');
INSERT INTO jugador VALUES (465,'DeSagana Diop','Oak Hill Academy HS','7-0',280,'C','Nets');
INSERT INTO jugador VALUES (466,'Devin Harris','Wisconsin','6-3',185,'G','Nets');
INSERT INTO jugador VALUES (467,'Trenton Hassell','Austin Peay','6-5',233,'F','Nets');
INSERT INTO jugador VALUES (468,'Richard Jefferson','Arizona','6-7',225,'F','Nets');
INSERT INTO jugador VALUES (469,'Nenad Krstic','Serbia Montenegro','7-0',240,'F-C','Nets');
INSERT INTO jugador VALUES (470,'Bostjan Nachbar','Slovenia','6-9',221,'F','Nets');
INSERT INTO jugador VALUES (471,'Stromile Swift','Louisiana State','6-10',220,'F-C','Nets');
INSERT INTO jugador VALUES (472,'Keith Van Horn','Utah','6-10',245,'F','Nets');
INSERT INTO jugador VALUES (473,'Marcus Williams','Connecticut','6-3',205,'G','Nets');
INSERT INTO jugador VALUES (474,'Sean Williams','Boston College','6-10',235,'F-C','Nets');
INSERT INTO jugador VALUES (481,'Carmelo Anthony','Syracuse','6-8',230,'F','Nuggets');
INSERT INTO jugador VALUES (482,'Chucky Atkins','South Florida','5-11',185,'G','Nuggets');
INSERT INTO jugador VALUES (483,'Marcus Camby','Massachuhsetts','6-11',235,'C','Nuggets');
INSERT INTO jugador VALUES (484,'Anthony Carter','Peppedirne','6-7',225,'G-F','Nuggets');
INSERT INTO jugador VALUES (485,'Yakhouba Diawarra','Pepperdine','6-7',225,'G-F','Nuggets');
INSERT INTO jugador VALUES (486,'Taurean Green','Florida','6-0',177,'G','Nuggets');
INSERT INTO jugador VALUES (487,'Steven Hunter','DePaul','7-0',240,'F-C','Nuggets');
INSERT INTO jugador VALUES (488,'Allen Iverson','Georgetown','6-0',180,'G','Nuggets');
INSERT INTO jugador VALUES (489,'Linas Kleiza','Missouri','6-8',245,'F-G','Nuggets');
INSERT INTO jugador VALUES (490,'Kenyon Martin','Cincinnati','6-9',240,'F','Nuggets');
INSERT INTO jugador VALUES (491,'Eduardo Najera','Oklahoma','6-8',235,'F','Nuggets');
INSERT INTO jugador VALUES (492,'Nene','Brazil','6-11',250,'F-C','Nuggets');
INSERT INTO jugador VALUES (493,'JR Smith','St.Benedits','6-6',220,'G','Nuggets');
INSERT INTO jugador VALUES (500,'Morris Almond','Rice','6-6',225,'G','Jazz');
INSERT INTO jugador VALUES (501,'Carlos Boozer','Duke','6-9',266,'F','Jazz');
INSERT INTO jugador VALUES (502,'Ronnie Brewer','Arkansas','6-7',223,'G','Jazz');
INSERT INTO jugador VALUES (503,'Jarron Collins','Stanfor','6-11',239,'C','Jazz');
INSERT INTO jugador VALUES (504,'Kyrylo Fesenko','Ukranie','7-1',288,'C','Jazz');
INSERT INTO jugador VALUES (505,'Matt Harpring','Gerogia Tech','6-7',230,'F','Jazz');
INSERT INTO jugador VALUES (506,'Jason Hart','Syracuse','6-3',180,'G','Jazz');
INSERT INTO jugador VALUES (507,'Andrei Kirilenko','Russia','6-9',223,'F','Jazz');
INSERT INTO jugador VALUES (508,'Kyle Korver','Creighton','6-6',211,'F-G','Jazz');
INSERT INTO jugador VALUES (509,'C.J. Miles','Skyline HS','6-6',220,'F-G','Jazz');
INSERT INTO jugador VALUES (510,'Paul Millsap','Loisiana Tech','6-8',258,'F-C','Jazz');
INSERT INTO jugador VALUES (511,'Mehmet Okur','Turkey','6-11',263,'C','Jazz');
INSERT INTO jugador VALUES (512,'Ronnie Price','Utah Valley State','6-2',190,'G','Jazz');
INSERT INTO jugador VALUES (513,'Deron Williams','Illions','6-3',205,'G','Jazz');
INSERT INTO jugador VALUES (520,'Marquis Daniels','Auburn','6-6',200,'G','Pacers');
INSERT INTO jugador VALUES (521,'Travis Diener','Marquette','6-1',175,'G','Pacers');
INSERT INTO jugador VALUES (522,'Ike Diogu','Arizona State','6-8',255,'F','Pacers');
INSERT INTO jugador VALUES (523,'Mike Dunleavy','Duke','6-9',230,'F-G','Pacers');
INSERT INTO jugador VALUES (524,'Jeff Foster','Texas State','6-11',250,'C','Pacers');
INSERT INTO jugador VALUES (525,'Stephen Graham','Oklahoma State','6-6',215,'G','Pacers');
INSERT INTO jugador VALUES (526,'Danny Granger','New Mexico','6-8',228,'F-G','Pacers');
INSERT INTO jugador VALUES (527,'David Harrison','Colorado','7-0',280,'C','Pacers');
INSERT INTO jugador VALUES (528,'Troy Murphy','Notre Dame','6-11',245,'C-F','Pacers');
INSERT INTO jugador VALUES (529,'Ronald Murray','Shaw','6-3',197,'G','Pacers');
INSERT INTO jugador VALUES (530,'Jermaine O''Neal','au Claire HS (SC)','6-11',260,'F-C','Pacers');
INSERT INTO jugador VALUES (531,'Andre Owens','Houston','6-4',200,'G','Pacers');
INSERT INTO jugador VALUES (532,'Kareem Rush','Missouri','6-6',215,'G','Pacers');
INSERT INTO jugador VALUES (533,'Jamaal Tinsley','Iowa State','6-3',185,'G','Pacers');
INSERT INTO jugador VALUES (534,'Shawne Williams','Memphis','6-9',225,'F','Pacers');
INSERT INTO jugador VALUES (540,'Arron Afflalo','UCLA','6-5',215,'G','Pistons');
INSERT INTO jugador VALUES (541,'Chauncey Billups','Colorado','6-3',202,'G','Pistons');
INSERT INTO jugador VALUES (542,'Juan Dixon','Maryland','6-3',165,'G','Pistons');
INSERT INTO jugador VALUES (543,'Richard Hamilton','Connecticut','6-7',193,'G','Pistons');
INSERT INTO jugador VALUES (544,'Jarvis Hayes','Georgia','6-8',228,'F','Pistons');
INSERT INTO jugador VALUES (545,'Walter Herrmann','Argentina','6-9',225,'F','Pistons');
INSERT INTO jugador VALUES (546,'Lindsey Hunter','Jackson State','6-2',195,'G','Pistons');
INSERT INTO jugador VALUES (547,'Amir Johnson','Westchester HS','6-9',210,'F','Pistons');
INSERT INTO jugador VALUES (548,'Jason Maxiell','Cincinnati','6-7',260,'F','Pistons');
INSERT INTO jugador VALUES (549,'Antonio McDyess','Alabama','6-9',245,'F','Pistons');
INSERT INTO jugador VALUES (550,'Tayshaun Prince','Kentucky','6-9',215,'F','Pistons');
INSERT INTO jugador VALUES (551,'Theo Ratliff','Wyoming','6-10',235,'C','Pistons');
INSERT INTO jugador VALUES (552,'Cheikh Samb','Senegal','7-1',245,'C','Pistons');
INSERT INTO jugador VALUES (553,'Rodney Stuckey','Eastern Washington','6-5',205,'G','Pistons');
INSERT INTO jugador VALUES (554,'Rasheed Wallace','North Carolina','6-11',230,'C-F','Pistons');
INSERT INTO jugador VALUES (560,'Nick Collison','Kansas','6-10',255,'F-C','Supersonics');
INSERT INTO jugador VALUES (561,'Ronald Dupree','Louisiana State','6-7',209,'F','Supersonics');
INSERT INTO jugador VALUES (562,'Kevin Durant','Texas','6-9',215,'G','Supersonics');
INSERT INTO jugador VALUES (563,'Francisco Elson','California','7-0',235,'C','Supersonics');
INSERT INTO jugador VALUES (564,'Mickael Gelabale','France','6-7',215,'F','Supersonics');
INSERT INTO jugador VALUES (565,'Jeff Green','Georgetown','6-9',235,'F','Supersonics');
INSERT INTO jugador VALUES (566,'Adrian Griffin','Seton Hall','6-5',230,'G-F','Supersonics');
INSERT INTO jugador VALUES (567,'Donyell Marshall','Connecticut','6-9',245,'F','Supersonics');
INSERT INTO jugador VALUES (568,'Johan Petro','France','7-0',247,'C','Supersonics');
INSERT INTO jugador VALUES (569,'Luke Ridnour','Oregon','6-2',175,'G','Supersonics');
INSERT INTO jugador VALUES (570,'Mouhamed Sene','Senegal','6-11',230,'C','Supersonics');
INSERT INTO jugador VALUES (571,'Robert Swift','Bakersfield HS','7-1',245,'C','Supersonics');
INSERT INTO jugador VALUES (572,'Earl Watson','UCLA','6-1',185,'G','Supersonics');
INSERT INTO jugador VALUES (573,'Chris Wilcox','Maryland','6-10',235,'F','Supersonics');
INSERT INTO jugador VALUES (574,'Damien Wilkins','Georgia','6-6',225,'F-G','Supersonics');
INSERT INTO jugador VALUES (580,'Leandro Barbosa','Brazil','6-3',202,'G','Suns');
INSERT INTO jugador VALUES (581,'Raja Bell','Florida Internationa','6-5',215,'G','Suns');
INSERT INTO jugador VALUES (582,'Boris Diaw','France','6-8',235,'F-C','Suns');
INSERT INTO jugador VALUES (583,'Gordan Giricek','Croatia','6-6',220,'G','Suns');
INSERT INTO jugador VALUES (584,'Grant Hill','Duke','6-8',225,'F-G','Suns');
INSERT INTO jugador VALUES (585,'Sean Marks','California','6-10',250,'F-C','Suns');
INSERT INTO jugador VALUES (586,'Steve Nash - C','Santa Clara','6-3',178,'G','Suns');
INSERT INTO jugador VALUES (587,'Shaquille ONeal','Louisiana State','7-1',325,'C','Suns');
INSERT INTO jugador VALUES (588,'Eric Piatkowski','Nebraska','6-7',215,'G-F','Suns');
INSERT INTO jugador VALUES (589,'Brian Skinner','Baylor','6-9',255,'G-F','Suns');
INSERT INTO jugador VALUES (590,'Amare Stoudemire','Cypress Creek (Orlan','6-10',249,'C-F','Suns');
INSERT INTO jugador VALUES (591,'D.J. Strawberry','Maryland','6-10',201,'G','Suns');
INSERT INTO jugador VALUES (592,'Alando Tucker','Wisconsin','6-6',205,'F','Suns');
INSERT INTO jugador VALUES (600,'Kelenna Azubuike',NULL,'6-5',220,'G-F','Warriors');
INSERT INTO jugador VALUES (601,'Matt Barnes',NULL,'6-7',226,'F','Warriors');
INSERT INTO jugador VALUES (602,'Marco Belinelli',NULL,'6-5',192,'G','Warriors');
INSERT INTO jugador VALUES (603,'Andris Biedrns',NULL,'6-11',230,'C','Warriors');
INSERT INTO jugador VALUES (604,'Austin Croshere',NULL,'6-10',235,'F','Warriors');
INSERT INTO jugador VALUES (605,'Baron Davis',NULL,'6-3',215,'G','Warriors');
INSERT INTO jugador VALUES (606,'Monta Ellis',NULL,'6-3',177,'G','Warriors');
INSERT INTO jugador VALUES (607,'Al Harrington',NULL,'6-9',250,'F-C','Warriors');
INSERT INTO jugador VALUES (608,'Stephen Jackson',NULL,'6-8',218,'F','Warriors');
INSERT INTO jugador VALUES (609,'Patrick O''Bryant',NULL,'7-0',250,'C','Warriors');
INSERT INTO jugador VALUES (610,'Kosta Perovic',NULL,'7-2',240,'C','Warriors');
INSERT INTO jugador VALUES (611,'Mickael Pietrus',NULL,'6-6',215,'F','Warriors');
INSERT INTO jugador VALUES (612,'C.J. Watson',NULL,'6-2',180,'G','Warriors');
INSERT INTO jugador VALUES (613,'Brandan Wright',NULL,'6-9',205,'F','Warriors');